import React from "react";

export const metadata = {
  title: "Kairo Dashboard",
  description: "Generated by create next app",
};

const Home = () => {
  return <div>HOME</div>;
};

export default Home;
